apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server
  namespace: workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-server
  template:
    metadata:
      labels:
        app: mcp-server
    spec:
      serviceAccountName: mcp-agent
      containers:
        - name: mcp-server
          image: {{ .Values.mcpServer.image }}
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
