apiVersion: v1
kind: Service
metadata:
  name: mcp-server
  namespace: workload
spec:
  selector:
    app: mcp-server
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000
